title: Rutvik Solanki | Mechancial Engineer
subtitle: A Mechanical Engineering Student at indian Institute of Technology, Delhi
description: >- # this means to ignore newlines until "baseurl:"
  This Description can be written using _config.yml file

url: "https://rutvik-solanki.ml" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Hire Me
      url : /shop
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.jpg
author: Rutvik Solanki
author_bio: Hi, my name is Rutvik Solanki. I am currently a Mechancial ENgineering student at Indian Institute of Technology, Delhi. I am also currrently interning with Reliance Industries as a Graduate Engineering Trainee for this summer.
author_email: "rutvikrj26@gmail.com"
author_location: India
author_website_url: "https://rutvik-solanki.ml"
typewrite-text: I am open to Internship oppurtunities in core mechanical Engineering and Design Consultancy jobs.

author_work_experiences:
            - company_name: Reliance Industries
              company_logo: ril.jfif
              company_url: https://www.ril.com
              designation: Graduate Engineering Trainee
              description: Worked on Designing of Lube oil Refiltration Systems
              visibility: true
            - company_name: RuTAG 
              company_logo: rutag.png
              company_url: https://rutag.iitd.ac.in
              designation: Coordinator
              description: Worked on various Rural Development Projects
              visibility: true

author_education_details:
              - college_logo: iitd.png
                college_name: Indian Institute of Technology, Delhi
                college_url: https://iitd.ac.in
                college_degree: Mechanical Engineering
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: farm.png
                project_title: Wind Farm Design Using ALM Technique
                project_description: The main Aim of the Project is to reduce the computational Cost involved in Wind Farm Design. There are two phases of the Project, First one involved gaining in depth, knowledge of the Wind Turbine Design, that completed early in the April. The second part is simulating one Wind Turbine using Actuator Line modelling Technique in Ansys Fluent. This is accomplished by using Ansys User Define Functions. This is almost Finished. Once validation completes, We will move on to Checking several Wind turbine arrangements for the Wind Farm Design. Using ALM Technique, it would be possible to simulate the Wind Farm in a considerable amount of time and computational power. One of the main aim of the Project was also to setup a framework to start the process of Low cost computational design for Wind Farm.
                project_url: https://consultrjtech.tk/contact
                visibility: true
              - project_thumbnail: biodiesel.png
                project_title: Design package for Mini-Biodiesel Reactor
                project_description: Our main goal in this project was to produce a design package(both software and hardware). A mathematical model with the variables time, amount of reactants and amount of catalyst was developed. The model was then coded using Matlab and Python(Open Sourced) to optimize the values of variables.Further, a gneneral Reactor design was taken and modified customly for our specific purpose. Then a Cost-Benefit analysis was also performed to ease the Manufacturing and reduce the overall cost.
                project_url: https://consultrjtech.tk/contact
                visibility: true
              - project_thumbnail: furnace.png
                project_title: Optimising Furnace Design for Hemispherical Furnace  
                project_description: This project mainly focuses on the development of a better, more efficient, more ergonomic and cost-efficient Furnace. A mathematical Model was created based on the physical working of the Furnace and then the coded version of the model in Matlab was used to optimize the design parameters.
                project_url: https://consultrjtech.tk/contact
                visibility: true
              - project_thumbnail: transmission.png
                project_title: Designing of a Formula Student Car's Transmission Box  
                project_description: This project was a part of my responsiblities as a junior engineer in Powertrain Department at Axlr8r Formula Racing - FSAE Club of IIT Delhi. A thorough study regarding the benefits and the issues of using several differnt transimissions were originally considered, after which followed an intense period of iterating through several design variables and finally defended my single stage planetary design to our Mentors(Professors). All the Design computations were performed using Ansys Static Structural and Rigid Body Dynamics Module. The lubricants were chosen from several possible options depending on the oil properties and added custom Extreme Pressure additives formulated by me in guidance of our Company partner.
                project_url: https://consultrjtech.tk/contact
                visibility: true
              - project_thumbnail: modelling.png
                project_title: vehicle Modelling in Matlab using Simulink - Simscape Toolbox  
                project_description: Earlier, for Designing our gear ratio, we depended on an open source Toolbox, which to say was not accurate. I pioneered and developed the vehicle modelling workflow for the first time. Though I faced several challenges while learning the toolbox, I would like to thank greatly, the free simscape toolbox introduction and demo vehicel modelling series. They did help me a lot in accomplishing the task at hand in stipulated time and with a considerably good efficeincy. This also led to further developments in Understanding of our motors and Motor Controllers at a more fundamental level giving us specific key insisghts into their performance and limits.
                project_url: https://consultrjtech.tk/contact
                visibility: true
                                
# social links
twitter_username: rutvikrj26
github_username:  Rutvikrj26
facebook_username: Rutvik Solanki
linkedin_username: Rutvik Solanki
behance_username: N/A
instagram_username: rutvikrj26
medium_username: N/A
telegram_username: Beyonder26
dribbble_username: N/A
flickr_username: N/A

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1152

# wakatime username (coding activity)
wakatime_username: rutvikrj26

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://rutvik-solanki.us10.list-manage.com/subscribe/post?u=33e4b00710c5857ba8afaa797&amp;id=5a24afdbc3

# formspree (contact form)
formspree_email: rutvikrj26@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
