title: Rutvik Solanki | Mechancial Engineer
subtitle: A Mechanical Engineering Student at indian Institute of Technology, Delhi
description: >- # this means to ignore newlines until "baseurl:"
  This Description can be written using _config.yml file

url: "https://rutvik-solanki.ml" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: startup
      url : https://consultrjtech.tk/contact
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Rutvik Solanki
author_bio: Hi, my name is Rutvik Solanki. I am currently a Mechancial ENgineering student at Indian Institute of Technology, Delhi. I am also currrently interning with Reliance Industries as a Graduate Engineering Trainee for this summer.
author_email: "rutvikrj26@gmail.com"
author_location: India
author_website_url: "https://rutvik-solanki.ml"
typewrite-text: I am open to Internship oppurtunities in core mechanical Engineering and Design Consultancy jobs.

author_work_experiences:
            - company_name: Reliance Industries
              company_logo: ril.jfif
              company_url: https://www.ril.com
              designation: Graduate Engineering Trainee
              description: Worked on Designing of Lube oil Refiltration Systems
              visibility: true
            - company_name: RuTAG 
              company_logo: rutag.png
              company_url: https://rutag.iitd.ac.in
              designation: Coordinator
              description: Worked on various Rural Development Projects
              visibility: true

author_education_details:
              - college_logo: iitd.png
                college_name: Indian Institute of Technology, Delhi
                college_url: https://iitd.ac.in
                college_degree: Mechanical Engineering
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: farm.png
                project_title: Wind Farm Design Using ALM Technique
                project_description: The main Aim of the Project is to reduce the computational Cost involved in Wind Farm Design. Read More in my Blogs 
                project_url: https://rutvik-solanki.ml/contact
                visibility: true
              - project_thumbnail: biodiesel.png
                project_title: Design package for Mini-Biodiesel Reactor
                project_description: Our main goal in this project was to produce a design package(both software and hardware). Read More in Blogs
                project_url: https://rutvik-solanki.ml/contact
                visibility: true
              - project_thumbnail: furnace.png
                project_title: Optimising Furnace Design for Hemispherical Furnace  
                project_description: This project mainly focuses on the development of a better, more efficient, more ergonomic and cost-efficient Furnace. Read more in my blogs
                project_url: https://rutvik-solanki.ml/contact
                visibility: true
              - project_thumbnail: transmission.png
                project_title: Designing of a Formula Student Car's Transmission Box  
                project_description: This project was a part of my responsiblities as a junior engineer in Powertrain Department at Axlr8r Formula Racing - FSAE Club of IIT Delhi. Read more in Blogs.
                project_url: https://rutvik-solanki.ml/contact
                visibility: true
              - project_thumbnail: modelling.png
                project_title: vehicle Modelling in Matlab using Simulink - Simscape Toolbox  
                project_description: This Project was focused on creating a Model for XLR-17 in Matlab.
                project_url: https://rutvik-solanki.ml/contact
                visibility: true

# social links
twitter_username: rutvikrj26
github_username:  Rutvikrj26
facebook_username: Rutvik Solanki
linkedin_username: Rutvik Solanki
behance_username: N/A
instagram_username: rutvikrj26
medium_username: N/A
telegram_username: Beyonder26
dribbble_username: N/A
flickr_username: N/A

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1152

# wakatime username (coding activity)
wakatime_username: rutvikrj26

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://rutvik-solanki.us10.list-manage.com/subscribe/post?u=33e4b00710c5857ba8afaa797&amp;id=5a24afdbc3

# formspree (contact form)
formspree_email: rutvikrj26@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
#defaults:
  -
#    scope:
#      path: "gallery"
#    values:
#      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
